// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwroybvmrydhswiztkbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3cm95YnZtcnlkaHN3aXp0a2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzU1NDMsImV4cCI6MjA2MTI1MTU0M30.uiQ6rdc5X33sBZehaZcFakqR2ISr3WqG3atRMjIarPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);